-- AlterTable
ALTER TABLE "ClassDay" ALTER COLUMN "time" SET DEFAULT '17:00';

-- AlterTable
ALTER TABLE "Subscription" ALTER COLUMN "startDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "paymentDate" SET DEFAULT CURRENT_TIMESTAMP;
